"""create loans table

Revision ID: 4d3ae88e78bc
Revises: 75d7032d45fe
Create Date: 2026-06-20 22:02:43.489704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3ae88e78bc'
down_revision: Union[str, Sequence[str], None] = '75d7032d45fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('interest_months', sa.Integer(), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
